name: Ssh Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_KEY }}
          port: ${{ secrets.AWS_EC2_PORT }}
          script: |
            ./deploy.sh
